### PR TITLE
Add k8s+etcd jenkins script

### PR DESCRIPTION
**Pull request by hongchaodeng**

### CODE REVIEW

**Comment by xiang90** [comment]
Where do we specify etcd3 in the script?

**Comment by hongchaodeng** [comment]
This is for the k8s-etcd3-e2e job.
We will need the GCE script to set up k8s cluster with etcd3.

I don't want to make the script too generic for other jobs too.

**Comment by xiang90** [comment]
Oh, OK. LGTM

**Comment by hongchaodeng** [comment]
This is working. I'm gonna merge this.
Note that this is just a work-around ;p 
In the long term, we should move to container image.

**Pull request merged**
